### ISSUE TITLE
Bedrock Claude doesn't have embedding

### ISSUE THREAD

**Issue by ConstantSun** [diptimanr/langchain_tests#1]
Hi,
I'm checking your pinecone_bedrock_1_pdf.ipynb, it looks so great. However, as Anthropic Claude docs [Can Claude do embedding](https://www.anthropic.com/product) and AWS Bedrock docs [bedrock embedding](https://docs.aws.amazon.com/bedrock/latest/userguide/embeddings.html) said, currently,

>  Bedrock supports one model for text embeddings, the Titan Embeddings G1 - Text model 

and 

> Can Claude do embeddings? - Not at this time! We find the open source SBERT embeddings to be good enough for most purposes.

Therefore, I don't know how can BedrockEmbeddings use Claude here:
<img width="1020" alt="image" src="https://github.com/diptimanr/langchain_tests/assets/26327367/498ec429-cccb-4869-9421-6468e73ecae3">

**Comment by diptimanr** [comment]
Hi ,

langchain.embeddings.BedrockEmbeddings uses amazon.titan-embed-text-v1 as the embedding model. I have only used the langchain wrapper, it still uses titan in the backend.
Hope it clarifies your question.

**Comment by ConstantSun** [comment]
Thank you,
So it uses Titan for the Text to embeddings part, and Claude for Text generation part ?

**Comment by diptimanr** [comment]
It uses Titan for text to embeddings part. 
For text generation you have a wide variety of LLMs to choose from like Claude-v2, AI21Labs Jurassic, Cohere etc.. Amazon Bedrock is the service which helps to provide APIs to call these LLMs.
